'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.4961
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("OrSe.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property db_addBlu() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("db_addBlu", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property db_addVerde() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("db_addVerde", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property DBFind() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DBFind", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property logo_finale() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("logo_finale", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property PDF() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PDF", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property printAllegatoA() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("printAllegatoA", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property printInterventi() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("printInterventi", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property printOP85() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("printOP85", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property printOP85_disabilitato() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("printOP85_disabilitato", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property pulsanteSoleGrigio() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pulsanteSoleGrigio", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property pulsanteSoleVerde() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pulsanteSoleVerde", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property reportAllegatoA() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("reportAllegatoA", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &apos;------------------------------------------------------------------------------
        '''&apos; &lt;auto-generated&gt;
        '''&apos;     This code was generated by a tool.
        '''&apos;     Runtime Version:2.0.50727.3603
        '''&apos;
        '''&apos;     Changes to this file may cause incorrect behavior and will be lost if
        '''&apos;     the code is regenerated.
        '''&apos; &lt;/auto-generated&gt;
        '''&apos;------------------------------------------------------------------------------
        '''
        '''Option Strict Off
        '''Option Explicit On
        '''
        '''Imports CrystalDecisions.CrystalReports.Engine
        '''Imports CrystalDecisions.R [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property reportAllegatoA1() As String
            Get
                Return ResourceManager.GetString("reportAllegatoA1", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property reportInterventi() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("reportInterventi", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &apos;------------------------------------------------------------------------------
        '''&apos; &lt;auto-generated&gt;
        '''&apos;     This code was generated by a tool.
        '''&apos;     Runtime Version:2.0.50727.3603
        '''&apos;
        '''&apos;     Changes to this file may cause incorrect behavior and will be lost if
        '''&apos;     the code is regenerated.
        '''&apos; &lt;/auto-generated&gt;
        '''&apos;------------------------------------------------------------------------------
        '''
        '''Option Strict Off
        '''Option Explicit On
        '''
        '''Imports CrystalDecisions.CrystalReports.Engine
        '''Imports CrystalDecisions.R [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property reportInterventi1() As String
            Get
                Return ResourceManager.GetString("reportInterventi1", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property reportOP85() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("reportOP85", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &apos;------------------------------------------------------------------------------
        '''&apos; &lt;auto-generated&gt;
        '''&apos;     This code was generated by a tool.
        '''&apos;     Runtime Version:2.0.50727.3603
        '''&apos;
        '''&apos;     Changes to this file may cause incorrect behavior and will be lost if
        '''&apos;     the code is regenerated.
        '''&apos; &lt;/auto-generated&gt;
        '''&apos;------------------------------------------------------------------------------
        '''
        '''Option Strict Off
        '''Option Explicit On
        '''
        '''Imports CrystalDecisions.CrystalReports.Engine
        '''Imports CrystalDecisions.R [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property reportOP851() As String
            Get
                Return ResourceManager.GetString("reportOP851", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property repubblica() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("repubblica", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property sagomaOFF() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sagomaOFF", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property sagomaON() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sagomaON", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property WORD() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("WORD", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
